version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - ALLOWED_ORIGIN=http://localhost:5173
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
